/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2018-07-30 09:05:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.tiles.admin_005ftile;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/finalproject_c/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/AuctionFinal/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1528076126070L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Header-->\r\n");
      out.write("        <header id=\"header\" class=\"header\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"header-menu\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-sm-7\">\r\n");
      out.write("                    <a id=\"menuToggle\" class=\"menutoggle pull-left\"><i class=\"fa fa fa-tasks\"></i></a>\r\n");
      out.write("                    <div class=\"header-left\">\r\n");
      out.write("                        <button class=\"search-trigger\"><i class=\"fa fa-search\"></i></button>\r\n");
      out.write("                        <div class=\"form-inline\">\r\n");
      out.write("                            <form class=\"search-form\">\r\n");
      out.write("                                <input class=\"form-control mr-sm-2\" type=\"text\" placeholder=\"Search ...\" aria-label=\"Search\">\r\n");
      out.write("                                <button class=\"search-close\" type=\"submit\"><i class=\"fa fa-close\"></i></button>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"dropdown for-notification\">\r\n");
      out.write("                          <button class=\"btn btn-secondary dropdown-toggle\" type=\"button\" id=\"notification\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                            <i class=\"fa fa-bell\"></i>\r\n");
      out.write("                            <span class=\"count bg-danger\">5</span>\r\n");
      out.write("                          </button>\r\n");
      out.write("                          <div class=\"dropdown-menu\" aria-labelledby=\"notification\">\r\n");
      out.write("                            <p class=\"red\">You have 3 Notification</p>\r\n");
      out.write("                            <a class=\"dropdown-item media bg-flat-color-1\" href=\"#\">\r\n");
      out.write("                                <i class=\"fa fa-check\"></i>\r\n");
      out.write("                                <p>Server #1 overloaded.</p>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <a class=\"dropdown-item media bg-flat-color-4\" href=\"#\">\r\n");
      out.write("                                <i class=\"fa fa-info\"></i>\r\n");
      out.write("                                <p>Server #2 overloaded.</p>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <a class=\"dropdown-item media bg-flat-color-5\" href=\"#\">\r\n");
      out.write("                                <i class=\"fa fa-warning\"></i>\r\n");
      out.write("                                <p>Server #3 overloaded.</p>\r\n");
      out.write("                            </a>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"dropdown for-message\">\r\n");
      out.write("                          <button class=\"btn btn-secondary dropdown-toggle\" type=\"button\"\r\n");
      out.write("                                id=\"message\"\r\n");
      out.write("                                data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                            <i class=\"ti-email\"></i>\r\n");
      out.write("                            <span class=\"count bg-primary\">9</span>\r\n");
      out.write("                          </button>\r\n");
      out.write("                          <div class=\"dropdown-menu\" aria-labelledby=\"message\">\r\n");
      out.write("                            <p class=\"red\">You have 4 Mails</p>\r\n");
      out.write("                            <a class=\"dropdown-item media bg-flat-color-1\" href=\"#\">\r\n");
      out.write("                                <span class=\"photo media-left\"><img alt=\"avatar\" src=\"");
      out.print(request.getContextPath());
      out.write("/resources/images/avatar/1.jpg\"></span>\r\n");
      out.write("                                <span class=\"message media-body\">\r\n");
      out.write("                                    <span class=\"name float-left\">Jonathan Smith</span>\r\n");
      out.write("                                    <span class=\"time float-right\">Just now</span>\r\n");
      out.write("                                        <p>Hello, this is an example msg</p>\r\n");
      out.write("                                </span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <a class=\"dropdown-item media bg-flat-color-4\" href=\"#\">\r\n");
      out.write("                                <span class=\"photo media-left\"><img alt=\"avatar\" src=\"");
      out.print(request.getContextPath());
      out.write("/resources/images/avatar/2.jpg\"></span>\r\n");
      out.write("                                <span class=\"message media-body\">\r\n");
      out.write("                                    <span class=\"name float-left\">Jack Sanders</span>\r\n");
      out.write("                                    <span class=\"time float-right\">5 minutes ago</span>\r\n");
      out.write("                                        <p>Lorem ipsum dolor sit amet, consectetur</p>\r\n");
      out.write("                                </span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <a class=\"dropdown-item media bg-flat-color-5\" href=\"#\">\r\n");
      out.write("                                <span class=\"photo media-left\"><img alt=\"avatar\" src=\"");
      out.print(request.getContextPath());
      out.write("/resources/images/avatar/3.jpg\"></span>\r\n");
      out.write("                                <span class=\"message media-body\">\r\n");
      out.write("                                    <span class=\"name float-left\">Cheryl Wheeler</span>\r\n");
      out.write("                                    <span class=\"time float-right\">10 minutes ago</span>\r\n");
      out.write("                                        <p>Hello, this is an example msg</p>\r\n");
      out.write("                                </span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <a class=\"dropdown-item media bg-flat-color-3\" href=\"#\">\r\n");
      out.write("                                <span class=\"photo media-left\"><img alt=\"avatar\" src=\"");
      out.print(request.getContextPath());
      out.write("/resources/images/avatar/4.jpg\"></span>\r\n");
      out.write("                                <span class=\"message media-body\">\r\n");
      out.write("                                    <span class=\"name float-left\">Rachel Santos</span>\r\n");
      out.write("                                    <span class=\"time float-right\">15 minutes ago</span>\r\n");
      out.write("                                        <p>Lorem ipsum dolor sit amet, consectetur</p>\r\n");
      out.write("                                </span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-sm-5\">\r\n");
      out.write("                    <div class=\"user-area dropdown float-right\">\r\n");
      out.write("                        <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                            <img class=\"user-avatar rounded-circle\" src=\"");
      out.print(request.getContextPath());
      out.write("/resources/images/admin.jpg\" alt=\"User Avatar\">\r\n");
      out.write("                        </a>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"user-menu dropdown-menu\">\r\n");
      out.write("                                <a class=\"nav-link\" href=\"#\"><i class=\"fa fa- user\"></i>My Profile</a>\r\n");
      out.write("\r\n");
      out.write("                                <a class=\"nav-link\" href=\"#\"><i class=\"fa fa- user\"></i>Notifications <span class=\"count\">13</span></a>\r\n");
      out.write("\r\n");
      out.write("                                <a class=\"nav-link\" href=\"#\"><i class=\"fa fa -cog\"></i>Settings</a>\r\n");
      out.write("\r\n");
      out.write("                                <a class=\"nav-link\" href=\"/auction/index.action\"><i class=\"fa fa-power -off\"></i>Logout</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"language-select dropdown\" id=\"language-select\">\r\n");
      out.write("                        <!-- <a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\"  id=\"language\" aria-haspopup=\"true\" aria-expanded=\"true\">\r\n");
      out.write("                            <i class=\"flag-icon flag-icon-us\"></i>\r\n");
      out.write("                        </a> -->\r\n");
      out.write("                        <div class=\"dropdown-menu\" aria-labelledby=\"language\" >\r\n");
      out.write("                            <div class=\"dropdown-item\">\r\n");
      out.write("                                <span class=\"flag-icon flag-icon-fr\"></span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"dropdown-item\">\r\n");
      out.write("                                <i class=\"flag-icon flag-icon-es\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"dropdown-item\">\r\n");
      out.write("                                <i class=\"flag-icon flag-icon-us\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"dropdown-item\">\r\n");
      out.write("                                <i class=\"flag-icon flag-icon-it\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </header><!-- /header -->\r\n");
      out.write("        <!-- Header-->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
