/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2018-07-31 01:08:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.auction;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.finalc.auction.model.CategoryVO;

public final class AddAuction_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/finalproject_c/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/AuctionFinal/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1528076126070L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.finalc.auction.model.CategoryVO");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<STYLE type=\"text/css\">\r\n");
      out.write("\t#addauction {\r\n");
      out.write("\t\twidth:800px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.names {\r\n");
      out.write("\t\ttext-align:right;\r\n");
      out.write("\t\tfont-weight:bold;\r\n");
      out.write("\t\tfont-size: 14pt;\r\n");
      out.write("\t}\r\n");
      out.write("</STYLE>\r\n");
      out.write("\r\n");
      out.write("<SCRIPT type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\tvar weatheRound = 0;\r\n");
      out.write("\r\n");
      out.write("\tjQuery(document).ready(function() {\r\n");
      out.write("\r\n");
      out.write("\t\tloopshowNowTime();\r\n");
      out.write("\t\t$(\"#category\").bind(\"change\", function(){\r\n");
      out.write("\t\t\tvar categoryIndex = \"\";\r\n");
      out.write("\t\t\tcategoryIndex += \"<option value=''>:::선택하세요:::</option>\";\r\n");
      out.write("\t\t\t");

			List<CategoryVO> cList = (List<CategoryVO>)session.getAttribute("categoryDetailList");
			
			for(CategoryVO cvo : cList){
				
      out.write("\r\n");
      out.write("\t\t\t\tif($(this).val() == ");
      out.print(cvo.getFk_cnum());
      out.write(")\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tcategoryIndex += \"<option value='");
      out.print( cvo.getCdnum() );
      out.write('\'');
      out.write('>');
      out.print( cvo.getCdname());
      out.write("</option>\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t");

			}
			
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#categoryDetail\").empty();\r\n");
      out.write("\t\t\t$(\"#categoryDetail\").append(categoryIndex);\r\n");
      out.write("\t\t}); // $(\"#category\").bind(\"change\", function()\r\n");
      out.write("\t}); // end of jQuery(document).ready(); ---------------------------------\r\n");
      out.write("\t\r\n");
      out.write("\tfunction showNowTime() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar now = new Date();\r\n");
      out.write("\t\r\n");
      out.write("\t\tvar strNow = now.getFullYear() + \"-\" + (now.getMonth() + 1) + \"-\" + now.getDate();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar hour = \"\";\r\n");
      out.write("\t\thour = \"&nbsp;\"+now.getHours()\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar minute = \"\";\r\n");
      out.write("\t\tif(now.getMinutes() < 10) {\r\n");
      out.write("\t\t\tminute = \"0\"+now.getMinutes();\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tminute = \"\"+now.getMinutes();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar second = \"\";\r\n");
      out.write("\t\tif(now.getSeconds() < 10) {\r\n");
      out.write("\t\t\tsecond = \"0\"+now.getSeconds();\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tsecond = \"\"+now.getSeconds();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tstrNow += hour + \":\" + minute + \":\" + second;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#clock\").html(\"<span style='color:#008899; font-weight:bold;'>\"+strNow+\"</span>\");\r\n");
      out.write("\t\r\n");
      out.write("\t}// end of function showNowTime() -----------------------------\r\n");
      out.write("\t\r\n");
      out.write("\tfunction loopshowNowTime() {\r\n");
      out.write("\t\tshowNowTime();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar timejugi = 1000;   // 시간을 1초 마다 자동 갱신하려고.\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tsetTimeout(function() {\r\n");
      out.write("\t\t\tloopshowNowTime();\t\r\n");
      out.write("\t\t}, timejugi);\r\n");
      out.write("\t\r\n");
      out.write("\t}// end of loopshowNowTime() --------------------------\r\n");
      out.write("\t\r\n");
      out.write("\tfunction categoryClick() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\talert(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${map.cnum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t} // function categoryClick()\r\n");
      out.write("\t\r\n");
      out.write("\tfunction submitForm() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 글제목 유효성 검사\r\n");
      out.write("\t\tvar actname = document.getElementById(\"actname\").value.trim();\r\n");
      out.write("\t\tif(actname == \"\") {\r\n");
      out.write("\t\t\talert(\"제목을 입력하세요.\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//스마트에디터 사용시 무의미하게 생기는 p태그 제거\r\n");
      out.write("        var content = document.getElementById(\"actd_content\");\r\n");
      out.write("        if(content.value == \"\" || content.value == \"<p>&nbsp;</p>\") {\r\n");
      out.write("        \talert(\"내용을 입력하세요\");\r\n");
      out.write("        \treturn;\r\n");
      out.write("        }\r\n");
      out.write("\t\t\r\n");
      out.write("        // 시간을 구한다!\r\n");
      out.write("        var now = new Date();\r\n");
      out.write("    \t\r\n");
      out.write("\t\tvar strNow = now.getFullYear() + \"-\" + (now.getMonth() + 1) + \"-\" + now.getDate();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar hour = \"\";\r\n");
      out.write("\t\thour = now.getHours()\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar minute = \"\";\r\n");
      out.write("\t\tif(now.getMinutes() < 10) {\r\n");
      out.write("\t\t\tminute = \"0\"+now.getMinutes();\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tminute = \"\"+now.getMinutes();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar starttime = strNow + \"T\" + hour + \":\" + minute;\r\n");
      out.write("        // 현재 시간을 구한다!!\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tconsole.log(\"starttime : \" + starttime);\r\n");
      out.write("\t\tvar actd_endday = document.getElementById(\"actd_endday\").value.trim();\r\n");
      out.write("\t\tconsole.log(\"actd_endday : \" + actd_endday);\r\n");
      out.write("\t\tif(actd_endday == \"\") {\r\n");
      out.write("\t\t\talert(\"종료시간을 입력하십시오...\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif((actd_endday - starttime) <= 0) {\r\n");
      out.write("\t\t\talert(\"종료시간을 정확히 입력해 주십시오...\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar startprice = document.getElementById(\"startprice\").value.trim();\r\n");
      out.write("\t\tif(startprice == \"\") {\r\n");
      out.write("\t\t\talert(\"경매시작가를 입력하십시오...\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar actd_price = document.getElementById(\"actd_price\").value.trim();\r\n");
      out.write("\t\tif(actd_price == \"\") {\r\n");
      out.write("\t\t\talert(\"즉시구매 가격을 입력하십시오...\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar actd_lowertenderprice = document.getElementById(\"actd_lowertenderprice\").value.trim();\r\n");
      out.write("\t\tif(actd_lowertenderprice == \"\") {\r\n");
      out.write("\t\t\talert(\"즉시입찰 가격을 입력하십시오...\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 엔터키 등을 변경\r\n");
      out.write("\t\tcontent.value = content.value.replace(/<p><br><\\/p>/gi, \"<br>\"); //<p><br></p> -> <br>로 변환\r\n");
      out.write("\t\tcontent.value = content.value.replace(/<\\/p><p>/gi, \"<br>\"); //</p><p> -> <br>로 변환\r\n");
      out.write("\t\tcontent.value = content.value.replace(/(<\\/p><br>|<p><br>)/gi, \"<br><br>\"); //</p><br>, <p><br> -> <br><br>로 변환\r\n");
      out.write("\t\tcontent.value = content.value.replace(/(<p>|<\\/p>)/gi, \"\"); //<p> 또는 </p> 모두 제거시\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// form 전송하기\r\n");
      out.write("\t\tvar frm = document.addAboutAuction;\r\n");
      out.write("\t\tfrm.action = \"");
      out.print(request.getContextPath());
      out.write("/AuctionUploadEnd.action\";\r\n");
      out.write("\t\tfrm.method = \"POST\";\r\n");
      out.write("\t\tfrm.submit();\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</SCRIPT>\r\n");
      out.write("\r\n");
      out.write("\t<form name=\"addAboutAuction\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t<div align=\"center\">\r\n");
      out.write("\t<table class=\"table\" id=\"addauction\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th class=\"names\">게시자 아이디</th>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginuser.usernum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"fk_usernum\"/>\r\n");
      out.write("\t\t\t\t<span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginuser.userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t\t<th class=\"names\">경매명</th>\r\n");
      out.write("\t\t\t<td><input type=\"text\" id=\"actname\" name=\"actname\"/></td>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("       \t\t<th class=\"names\">상품 이미지</th>\r\n");
      out.write("       \t\t<td><input type=\"file\" name=\"attach\"/></td>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t\t<th class=\"names\">대분류</th>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-5 col-sm-5\">\r\n");
      out.write("\t\t\t\t<select class=\"form-control\" id=\"category\" name=\"fk_cnum\">\r\n");
      out.write("\t\t\t\t\t<option value=\"\">:::선택하세요:::</option>\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t\t<th class=\"names\">상세분류</th>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-5 col-sm-5\">\r\n");
      out.write("\t\t\t\t\t<select class=\"form-control\" id=\"categoryDetail\" name=\"fk_cdnum\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"\">:::선택하세요:::</option>\r\n");
      out.write("\t\t            </select>\r\n");
      out.write("\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t\t<th class=\"names\">경매시작가격</th>\r\n");
      out.write("\t\t\t<td><input type=\"text\" id=\"startprice\" name=\"startprice\"/></td>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t\t<th class=\"names\">즉시구매가격</th>\r\n");
      out.write("\t\t\t<td><input type=\"text\" id=\"actd_price\" name=\"actd_price\" /></td>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t\t<th class=\"names\">최저입찰가</th>\r\n");
      out.write("\t\t\t<td><input type=\"text\" id=\"actd_lowertenderprice\" name=\"actd_lowertenderprice\" /></td>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t\t<th class=\"names\">경매시작일</th>\r\n");
      out.write("\t\t\t<td><div class=\"col-lg-5 col-sm-5\">\r\n");
      out.write("\t\t\t\t\t<div id=\"clock\" style=\"display:inline;\"></div>\r\n");
      out.write("\t\t\t\t</div></td>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t\t<th class=\"names\">경매종료일</th>\r\n");
      out.write("\t\t\t<td><div class=\"col-lg-8 col-sm-8\">\r\n");
      out.write("\t\t\t\t\t<input type=\"datetime-local\" id=\"actd_endday\" name=\"actd_endday\" class=\"form-control\" />\r\n");
      out.write("\t\t\t\t</div></td>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t\t<th class=\"names\">판매수량</th>\r\n");
      out.write("\t\t\t<td>  <input type=\"number\" id=\"actd_qty\" name=\"actd_qty\" min=\"1\" max=\"100\" step=\"1\" value=\"1\"></td>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t\t<th class=\"names\" colspan=\"2\" style=\"text-align:center;\">내용</th>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t\t<td colspan=\"2\"><div align=\"center\"><TEXTAREA id=\"actd_content\" name=\"actd_content\" rows=\"6\" cols=\"90%\"></TEXTAREA></div></td>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t<div align=\"center\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn\" onClick=\"submitForm()\">상품등록</button>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn\" onClick=\"javascript:history.back()\">취소</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<br/>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</form>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/auction/AddAuction.jsp(197,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("map");
      // /WEB-INF/views/auction/AddAuction.jsp(197,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/auction/AddAuction.jsp(197,5) '${categoryList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${categoryList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${map.cnum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" data-filter=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${map.cname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${map.cname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
